### ISSUE TITLE
Do you find a fix for this issue ?

### ISSUE THREAD

**Issue by mackoj** [neonichu/xcode-7.3-linker-issue#1]
Hi @neonichu,

Do you find a fix for this issue ? I have the same problem.

Cheers,

**Comment by neonichu** [comment]
No, for my concrete case I was able to remove `-ObjC` from my linker flags, because it wasn't actually needed. Let's hope the radar will be acted upon for the next release.

**Comment by neonichu** [comment]
This has been fixed in Xcode 7.3.1.
